# Generated by Django 4.2.7 on 2023-11-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mechanic_phone_alter_mechanic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40)),
                ('faulty_part', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
