# Generated by Django 4.2.7 on 2023-11-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_servicerequest_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
