# Generated by Django 4.2.7 on 2023-11-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tow'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
            ],
        ),
    ]
