# Generated by Django 4.2.7 on 2023-11-27 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
